#!/usr/bin/env python

Import('env')

common_sailfish = [
	"os_sailfish.cpp",
	"key_mapping_sailfish.cpp"
]

env.Program('#platform/sailfish_qt/project/godot', ['godot_sailfish.cpp'] + common_sailfish)
